server:
  port: 7001

#eureka服务端的实例名称
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去搜索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/                       #集群指向其他eureka ，单机指向自己
  #server:
    #出厂默认，自我保护机制是开启的 enable-self-preservation: true
    #enable-self-preservation: false                                        #关闭自我保护机制，保证不可用服务被及时清除
    #eviction-interval-timer-in-ms: 2000


